"""Input/output schemas for structure design tools."""

from __future__ import annotations

from pathlib import Path  # noqa: TC003 - Pydantic needs at runtime
from typing import Any

from pydantic import BaseModel, Field

from autobio.schemas.base import BaseInput, BaseOutput
from autobio.schemas.hints import Tier, Widget, ui


class StructureDesignInput(BaseInput):
    """Input schema for generative structure design tools (e.g., RFDiffusion3).

    Design specifications are provided as a dict of named specs, each containing
    tool-native configuration.  Input structure files are listed separately so the
    runner can copy them into the container workspace and rewrite paths.
    """

    input_structures: list[Path] = Field(
        default_factory=list,
        description=(
            "PDB or mmCIF files referenced by entries in design_specs. "
            "Each file is copied into the container workspace; 'input' values "
            "in design_specs are rewritten to container-internal paths."
        ),
    )
    design_specs: dict[str, dict[str, Any]] = Field(
        description=(
            "Named design specifications passed to the tool. Each key is a "
            "user-chosen name; each value is a dict of tool-native parameters "
            "(e.g., 'input', 'contig', 'length', 'select_hotspots', etc.)."
        ),
    )
    n_batches: int = Field(
        default=1,
        description="Number of independent design batches per specification.",
    )


class RFD3Input(BaseInput):
    """Input for RFDiffusion3 generative structure design (single ``generate`` mode)."""

    design_specs: dict[str, dict[str, Any]] = Field(
        description=(
            "Named design specifications; each value is a dict of RFD3-native "
            "parameters. Common keys: 'input' (target structure filename, must match "
            "an input_structures file), 'contig' (which residues to keep vs design — "
            "chain+range keeps input e.g. 'A1-10', a bare integer/range designs new "
            "e.g. '120-130', '/0' is a chain break), 'length' (e.g. '100' or '80-120'), "
            "the 'select_*' fields (select_fixed_atoms/select_hotspots/select_buried/… "
            "each accept a bool, a contig string, or a {residue_id: atom_names} dict; "
            "atom keywords BKBN/ALL/TIP), 'symmetry' ({'id': 'C3'} — C/D groups), "
            "'partial_t' (noise Å, 5-15), 'ligand', 'unindex', 'infer_ori_strategy' "
            "('com'|'hotspots'), 'is_non_loopy'. See the tool notes for use-case recipes."
        ),
        json_schema_extra=ui(widget=Widget.TEXTAREA, tier=Tier.PRIMARY, order=0),
    )
    input_structures: list[Path] = Field(
        default_factory=list,
        description=(
            "PDB/mmCIF files referenced by design_specs 'input' values. Each is copied "
            "into the workspace and its 'input' path is rewritten to a container path."
        ),
        json_schema_extra=ui(widget=Widget.FILE, tier=Tier.PRIMARY, order=1),
    )
    n_batches: int = Field(
        default=1,
        description="Number of independent design batches per specification.",
        json_schema_extra=ui(widget=Widget.NUMBER, tier=Tier.ADVANCED, order=10),
    )


class DesignedStructure(BaseModel):
    """A single structure generated by a design tool."""

    spec_name: str = Field(
        description="Name of the design specification that produced this structure.",
    )
    batch_index: int = Field(description="Batch index within the specification.")
    design_index: int = Field(description="Design index within the batch.")
    structure_path: Path = Field(
        description="Path to the designed structure (CIF) in outputs/standardized/.",
    )
    diffusion_metadata: dict[str, Any] | None = Field(
        default=None,
        description=(
            "Per-design metadata from the tool (residue mapping, timing, "
            "specification echo-back, etc.)."
        ),
    )
    evaluation_metrics: dict[str, Any] | None = Field(
        default=None,
        description=(
            "Per-design evaluation metrics from the full design pipeline. "
            "Includes AF2 iPTM/pTM/pLDDT, RF3 scores, MPNN recovery metrics, "
            "and scRMSD. None when mode='generate'."
        ),
    )


class StructureDesignOutput(BaseOutput):
    """Output schema for generative structure design tools."""

    designs: list[DesignedStructure] = Field(
        description="Generated structures across all specifications and batches.",
    )
    spec_summary: dict[str, int] = Field(
        description="Mapping of specification name to the number of designs produced.",
    )
