"""Input/output schemas for structure design tools."""

from __future__ import annotations

from pathlib import Path  # noqa: TC003 - Pydantic needs at runtime
from typing import Any

from pydantic import BaseModel, Field

from autobio.schemas.base import BaseInput, BaseOutput


class StructureDesignInput(BaseInput):
    """Input schema for generative structure design tools (e.g., RFDiffusion3).

    Design specifications are provided as a dict of named specs, each containing
    tool-native configuration.  Input structure files are listed separately so the
    runner can copy them into the container workspace and rewrite paths.
    """

    input_structures: list[Path] = Field(
        default_factory=list,
        description=(
            "PDB or mmCIF files referenced by entries in design_specs. "
            "Each file is copied into the container workspace; 'input' values "
            "in design_specs are rewritten to container-internal paths."
        ),
    )
    design_specs: dict[str, dict[str, Any]] = Field(
        description=(
            "Named design specifications passed to the tool. Each key is a "
            "user-chosen name; each value is a dict of tool-native parameters "
            "(e.g., 'input', 'contig', 'length', 'select_hotspots', etc.)."
        ),
    )
    n_batches: int = Field(
        default=1,
        description="Number of independent design batches per specification.",
    )


class DesignedStructure(BaseModel):
    """A single structure generated by a design tool."""

    spec_name: str = Field(
        description="Name of the design specification that produced this structure.",
    )
    batch_index: int = Field(description="Batch index within the specification.")
    design_index: int = Field(description="Design index within the batch.")
    structure_path: Path = Field(
        description="Path to the designed structure (CIF) in outputs/standardized/.",
    )
    diffusion_metadata: dict[str, Any] | None = Field(
        default=None,
        description=(
            "Per-design metadata from the tool (residue mapping, timing, "
            "specification echo-back, etc.)."
        ),
    )
    evaluation_metrics: dict[str, Any] | None = Field(
        default=None,
        description=(
            "Per-design evaluation metrics from the full design pipeline. "
            "Includes AF2 iPTM/pTM/pLDDT, RF3 scores, MPNN recovery metrics, "
            "and scRMSD. None when mode='generate'."
        ),
    )


class StructureDesignOutput(BaseOutput):
    """Output schema for generative structure design tools."""

    designs: list[DesignedStructure] = Field(
        description="Generated structures across all specifications and batches.",
    )
    spec_summary: dict[str, int] = Field(
        description="Mapping of specification name to the number of designs produced.",
    )
